/* eslint-disable */
/**
 * @fileoverview gRPC-Web generated client stub for watchclub
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.0
// source: v1.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.watchclub = require('./v1_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.watchclub.WatchClubServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.watchclub.WatchClubServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.CreateUserRequest,
 *   !proto.watchclub.CreateUserResponse>}
 */
const methodDescriptor_WatchClubService_CreateUser = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.watchclub.CreateUserRequest,
  proto.watchclub.CreateUserResponse,
  /**
   * @param {!proto.watchclub.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.CreateUserResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.CreateUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.CreateUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_CreateUser,
      callback);
};


/**
 * @param {!proto.watchclub.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.CreateUserResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.GetUserRequest,
 *   !proto.watchclub.GetUserResponse>}
 */
const methodDescriptor_WatchClubService_GetUser = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/GetUser',
  grpc.web.MethodType.UNARY,
  proto.watchclub.GetUserRequest,
  proto.watchclub.GetUserResponse,
  /**
   * @param {!proto.watchclub.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.GetUserResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.GetUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.GetUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.getUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/GetUser',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetUser,
      callback);
};


/**
 * @param {!proto.watchclub.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.GetUserResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.getUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/GetUser',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.CreateClubRequest,
 *   !proto.watchclub.CreateClubResponse>}
 */
const methodDescriptor_WatchClubService_CreateClub = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/CreateClub',
  grpc.web.MethodType.UNARY,
  proto.watchclub.CreateClubRequest,
  proto.watchclub.CreateClubResponse,
  /**
   * @param {!proto.watchclub.CreateClubRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.CreateClubResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.CreateClubRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.CreateClubResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.CreateClubResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.createClub =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/CreateClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_CreateClub,
      callback);
};


/**
 * @param {!proto.watchclub.CreateClubRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.CreateClubResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.createClub =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/CreateClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_CreateClub);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.JoinClubRequest,
 *   !proto.watchclub.JoinClubResponse>}
 */
const methodDescriptor_WatchClubService_JoinClub = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/JoinClub',
  grpc.web.MethodType.UNARY,
  proto.watchclub.JoinClubRequest,
  proto.watchclub.JoinClubResponse,
  /**
   * @param {!proto.watchclub.JoinClubRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.JoinClubResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.JoinClubRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.JoinClubResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.JoinClubResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.joinClub =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/JoinClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_JoinClub,
      callback);
};


/**
 * @param {!proto.watchclub.JoinClubRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.JoinClubResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.joinClub =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/JoinClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_JoinClub);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.AddPickRequest,
 *   !proto.watchclub.AddPickResponse>}
 */
const methodDescriptor_WatchClubService_AddPick = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/AddPick',
  grpc.web.MethodType.UNARY,
  proto.watchclub.AddPickRequest,
  proto.watchclub.AddPickResponse,
  /**
   * @param {!proto.watchclub.AddPickRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.AddPickResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.AddPickRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.AddPickResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.AddPickResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.addPick =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/AddPick',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_AddPick,
      callback);
};


/**
 * @param {!proto.watchclub.AddPickRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.AddPickResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.addPick =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/AddPick',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_AddPick);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.DeletePickRequest,
 *   !proto.watchclub.DeletePickResponse>}
 */
const methodDescriptor_WatchClubService_DeletePick = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/DeletePick',
  grpc.web.MethodType.UNARY,
  proto.watchclub.DeletePickRequest,
  proto.watchclub.DeletePickResponse,
  /**
   * @param {!proto.watchclub.DeletePickRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.DeletePickResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.DeletePickRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.DeletePickResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.DeletePickResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.deletePick =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/DeletePick',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_DeletePick,
      callback);
};


/**
 * @param {!proto.watchclub.DeletePickRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.DeletePickResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.deletePick =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/DeletePick',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_DeletePick);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.GetClubRequest,
 *   !proto.watchclub.GetClubResponse>}
 */
const methodDescriptor_WatchClubService_GetClub = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/GetClub',
  grpc.web.MethodType.UNARY,
  proto.watchclub.GetClubRequest,
  proto.watchclub.GetClubResponse,
  /**
   * @param {!proto.watchclub.GetClubRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.GetClubResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.GetClubRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.GetClubResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.GetClubResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.getClub =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/GetClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetClub,
      callback);
};


/**
 * @param {!proto.watchclub.GetClubRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.GetClubResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.getClub =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/GetClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetClub);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.StartClubRequest,
 *   !proto.watchclub.StartClubResponse>}
 */
const methodDescriptor_WatchClubService_StartClub = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/StartClub',
  grpc.web.MethodType.UNARY,
  proto.watchclub.StartClubRequest,
  proto.watchclub.StartClubResponse,
  /**
   * @param {!proto.watchclub.StartClubRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.StartClubResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.StartClubRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.StartClubResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.StartClubResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.startClub =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/StartClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_StartClub,
      callback);
};


/**
 * @param {!proto.watchclub.StartClubRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.StartClubResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.startClub =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/StartClub',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_StartClub);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.GetScheduledPicksRequest,
 *   !proto.watchclub.GetScheduledPicksResponse>}
 */
const methodDescriptor_WatchClubService_GetScheduledPicks = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/GetScheduledPicks',
  grpc.web.MethodType.UNARY,
  proto.watchclub.GetScheduledPicksRequest,
  proto.watchclub.GetScheduledPicksResponse,
  /**
   * @param {!proto.watchclub.GetScheduledPicksRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.GetScheduledPicksResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.GetScheduledPicksRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.GetScheduledPicksResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.GetScheduledPicksResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.getScheduledPicks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/GetScheduledPicks',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetScheduledPicks,
      callback);
};


/**
 * @param {!proto.watchclub.GetScheduledPicksRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.GetScheduledPicksResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.getScheduledPicks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/GetScheduledPicks',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetScheduledPicks);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.SendLoginEmailRequest,
 *   !proto.watchclub.SendLoginEmailResponse>}
 */
const methodDescriptor_WatchClubService_SendLoginEmail = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/SendLoginEmail',
  grpc.web.MethodType.UNARY,
  proto.watchclub.SendLoginEmailRequest,
  proto.watchclub.SendLoginEmailResponse,
  /**
   * @param {!proto.watchclub.SendLoginEmailRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.SendLoginEmailResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.SendLoginEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.SendLoginEmailResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.SendLoginEmailResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.sendLoginEmail =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/SendLoginEmail',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_SendLoginEmail,
      callback);
};


/**
 * @param {!proto.watchclub.SendLoginEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.SendLoginEmailResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.sendLoginEmail =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/SendLoginEmail',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_SendLoginEmail);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.watchclub.GetClubCalendarRequest,
 *   !proto.watchclub.GetClubCalendarResponse>}
 */
const methodDescriptor_WatchClubService_GetClubCalendar = new grpc.web.MethodDescriptor(
  '/watchclub.WatchClubService/GetClubCalendar',
  grpc.web.MethodType.UNARY,
  proto.watchclub.GetClubCalendarRequest,
  proto.watchclub.GetClubCalendarResponse,
  /**
   * @param {!proto.watchclub.GetClubCalendarRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.watchclub.GetClubCalendarResponse.deserializeBinary
);


/**
 * @param {!proto.watchclub.GetClubCalendarRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.watchclub.GetClubCalendarResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.watchclub.GetClubCalendarResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.watchclub.WatchClubServiceClient.prototype.getClubCalendar =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/watchclub.WatchClubService/GetClubCalendar',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetClubCalendar,
      callback);
};


/**
 * @param {!proto.watchclub.GetClubCalendarRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.watchclub.GetClubCalendarResponse>}
 *     Promise that resolves to the response
 */
proto.watchclub.WatchClubServicePromiseClient.prototype.getClubCalendar =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/watchclub.WatchClubService/GetClubCalendar',
      request,
      metadata || {},
      methodDescriptor_WatchClubService_GetClubCalendar);
};


module.exports = proto.watchclub;

