// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: v1.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatchClubServiceClient is the client API for WatchClubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchClubServiceClient interface {
	// CreateUser creates a new user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// GetUser gets a user by ID
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// CreateClub creates a new movie club
	CreateClub(ctx context.Context, in *CreateClubRequest, opts ...grpc.CallOption) (*CreateClubResponse, error)
	// JoinClub adds a user to a club
	JoinClub(ctx context.Context, in *JoinClubRequest, opts ...grpc.CallOption) (*JoinClubResponse, error)
	// AddMoviePick adds a movie pick to a club
	AddMoviePick(ctx context.Context, in *AddMoviePickRequest, opts ...grpc.CallOption) (*AddMoviePickResponse, error)
	// GetClub gets details about a club including members and their picks
	GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error)
	// StartClub shuffles all picks and generates the weekly viewing schedule
	StartClub(ctx context.Context, in *StartClubRequest, opts ...grpc.CallOption) (*StartClubResponse, error)
	// GetWeeklyAssignments gets the weekly movie viewing schedule for a club
	GetWeeklyAssignments(ctx context.Context, in *GetWeeklyAssignmentsRequest, opts ...grpc.CallOption) (*GetWeeklyAssignmentsResponse, error)
	// SendRecoveryEmail sends an account recovery email with a login link
	SendRecoveryEmail(ctx context.Context, in *SendRecoveryEmailRequest, opts ...grpc.CallOption) (*SendRecoveryEmailResponse, error)
}

type watchClubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchClubServiceClient(cc grpc.ClientConnInterface) WatchClubServiceClient {
	return &watchClubServiceClient{cc}
}

func (c *watchClubServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) CreateClub(ctx context.Context, in *CreateClubRequest, opts ...grpc.CallOption) (*CreateClubResponse, error) {
	out := new(CreateClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/CreateClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) JoinClub(ctx context.Context, in *JoinClubRequest, opts ...grpc.CallOption) (*JoinClubResponse, error) {
	out := new(JoinClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/JoinClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) AddMoviePick(ctx context.Context, in *AddMoviePickRequest, opts ...grpc.CallOption) (*AddMoviePickResponse, error) {
	out := new(AddMoviePickResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/AddMoviePick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error) {
	out := new(GetClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) StartClub(ctx context.Context, in *StartClubRequest, opts ...grpc.CallOption) (*StartClubResponse, error) {
	out := new(StartClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/StartClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetWeeklyAssignments(ctx context.Context, in *GetWeeklyAssignmentsRequest, opts ...grpc.CallOption) (*GetWeeklyAssignmentsResponse, error) {
	out := new(GetWeeklyAssignmentsResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetWeeklyAssignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) SendRecoveryEmail(ctx context.Context, in *SendRecoveryEmailRequest, opts ...grpc.CallOption) (*SendRecoveryEmailResponse, error) {
	out := new(SendRecoveryEmailResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/SendRecoveryEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchClubServiceServer is the server API for WatchClubService service.
// All implementations must embed UnimplementedWatchClubServiceServer
// for forward compatibility
type WatchClubServiceServer interface {
	// CreateUser creates a new user
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// GetUser gets a user by ID
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// CreateClub creates a new movie club
	CreateClub(context.Context, *CreateClubRequest) (*CreateClubResponse, error)
	// JoinClub adds a user to a club
	JoinClub(context.Context, *JoinClubRequest) (*JoinClubResponse, error)
	// AddMoviePick adds a movie pick to a club
	AddMoviePick(context.Context, *AddMoviePickRequest) (*AddMoviePickResponse, error)
	// GetClub gets details about a club including members and their picks
	GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error)
	// StartClub shuffles all picks and generates the weekly viewing schedule
	StartClub(context.Context, *StartClubRequest) (*StartClubResponse, error)
	// GetWeeklyAssignments gets the weekly movie viewing schedule for a club
	GetWeeklyAssignments(context.Context, *GetWeeklyAssignmentsRequest) (*GetWeeklyAssignmentsResponse, error)
	// SendRecoveryEmail sends an account recovery email with a login link
	SendRecoveryEmail(context.Context, *SendRecoveryEmailRequest) (*SendRecoveryEmailResponse, error)
	mustEmbedUnimplementedWatchClubServiceServer()
}

// UnimplementedWatchClubServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatchClubServiceServer struct {
}

func (UnimplementedWatchClubServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedWatchClubServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedWatchClubServiceServer) CreateClub(context.Context, *CreateClubRequest) (*CreateClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClub not implemented")
}
func (UnimplementedWatchClubServiceServer) JoinClub(context.Context, *JoinClubRequest) (*JoinClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinClub not implemented")
}
func (UnimplementedWatchClubServiceServer) AddMoviePick(context.Context, *AddMoviePickRequest) (*AddMoviePickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMoviePick not implemented")
}
func (UnimplementedWatchClubServiceServer) GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClub not implemented")
}
func (UnimplementedWatchClubServiceServer) StartClub(context.Context, *StartClubRequest) (*StartClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClub not implemented")
}
func (UnimplementedWatchClubServiceServer) GetWeeklyAssignments(context.Context, *GetWeeklyAssignmentsRequest) (*GetWeeklyAssignmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeeklyAssignments not implemented")
}
func (UnimplementedWatchClubServiceServer) SendRecoveryEmail(context.Context, *SendRecoveryEmailRequest) (*SendRecoveryEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRecoveryEmail not implemented")
}
func (UnimplementedWatchClubServiceServer) mustEmbedUnimplementedWatchClubServiceServer() {}

// UnsafeWatchClubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchClubServiceServer will
// result in compilation errors.
type UnsafeWatchClubServiceServer interface {
	mustEmbedUnimplementedWatchClubServiceServer()
}

func RegisterWatchClubServiceServer(s grpc.ServiceRegistrar, srv WatchClubServiceServer) {
	s.RegisterService(&WatchClubService_ServiceDesc, srv)
}

func _WatchClubService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_CreateClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).CreateClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/CreateClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).CreateClub(ctx, req.(*CreateClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_JoinClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).JoinClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/JoinClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).JoinClub(ctx, req.(*JoinClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_AddMoviePick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMoviePickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).AddMoviePick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/AddMoviePick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).AddMoviePick(ctx, req.(*AddMoviePickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetClub(ctx, req.(*GetClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_StartClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).StartClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/StartClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).StartClub(ctx, req.(*StartClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetWeeklyAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetWeeklyAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetWeeklyAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetWeeklyAssignments(ctx, req.(*GetWeeklyAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_SendRecoveryEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRecoveryEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).SendRecoveryEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/SendRecoveryEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).SendRecoveryEmail(ctx, req.(*SendRecoveryEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchClubService_ServiceDesc is the grpc.ServiceDesc for WatchClubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchClubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchclub.WatchClubService",
	HandlerType: (*WatchClubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _WatchClubService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _WatchClubService_GetUser_Handler,
		},
		{
			MethodName: "CreateClub",
			Handler:    _WatchClubService_CreateClub_Handler,
		},
		{
			MethodName: "JoinClub",
			Handler:    _WatchClubService_JoinClub_Handler,
		},
		{
			MethodName: "AddMoviePick",
			Handler:    _WatchClubService_AddMoviePick_Handler,
		},
		{
			MethodName: "GetClub",
			Handler:    _WatchClubService_GetClub_Handler,
		},
		{
			MethodName: "StartClub",
			Handler:    _WatchClubService_StartClub_Handler,
		},
		{
			MethodName: "GetWeeklyAssignments",
			Handler:    _WatchClubService_GetWeeklyAssignments_Handler,
		},
		{
			MethodName: "SendRecoveryEmail",
			Handler:    _WatchClubService_SendRecoveryEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.proto",
}
