// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: v1.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatchClubServiceClient is the client API for WatchClubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchClubServiceClient interface {
	// CreateUser creates a new user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// GetUser gets a user by ID
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// CreateClub creates a new watch club
	CreateClub(ctx context.Context, in *CreateClubRequest, opts ...grpc.CallOption) (*CreateClubResponse, error)
	// JoinClub adds a user to a club
	JoinClub(ctx context.Context, in *JoinClubRequest, opts ...grpc.CallOption) (*JoinClubResponse, error)
	// AddPick adds a pick to a club
	AddPick(ctx context.Context, in *AddPickRequest, opts ...grpc.CallOption) (*AddPickResponse, error)
	// DeletePick removes a pick from a club (only allowed before club starts)
	DeletePick(ctx context.Context, in *DeletePickRequest, opts ...grpc.CallOption) (*DeletePickResponse, error)
	// GetClub gets details about a club including members and their picks
	GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error)
	// StartClub shuffles all picks and generates the weekly viewing schedule
	StartClub(ctx context.Context, in *StartClubRequest, opts ...grpc.CallOption) (*StartClubResponse, error)
	// GetScheduledPicks gets the schedule for a club
	GetScheduledPicks(ctx context.Context, in *GetScheduledPicksRequest, opts ...grpc.CallOption) (*GetScheduledPicksResponse, error)
	// SendLoginEmail sends an account login email
	SendLoginEmail(ctx context.Context, in *SendLoginEmailRequest, opts ...grpc.CallOption) (*SendLoginEmailResponse, error)
	// GetClubCalendar generates an ICS calendar file for a club's schedule
	GetClubCalendar(ctx context.Context, in *GetClubCalendarRequest, opts ...grpc.CallOption) (*GetClubCalendarResponse, error)
}

type watchClubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchClubServiceClient(cc grpc.ClientConnInterface) WatchClubServiceClient {
	return &watchClubServiceClient{cc}
}

func (c *watchClubServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) CreateClub(ctx context.Context, in *CreateClubRequest, opts ...grpc.CallOption) (*CreateClubResponse, error) {
	out := new(CreateClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/CreateClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) JoinClub(ctx context.Context, in *JoinClubRequest, opts ...grpc.CallOption) (*JoinClubResponse, error) {
	out := new(JoinClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/JoinClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) AddPick(ctx context.Context, in *AddPickRequest, opts ...grpc.CallOption) (*AddPickResponse, error) {
	out := new(AddPickResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/AddPick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) DeletePick(ctx context.Context, in *DeletePickRequest, opts ...grpc.CallOption) (*DeletePickResponse, error) {
	out := new(DeletePickResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/DeletePick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetClub(ctx context.Context, in *GetClubRequest, opts ...grpc.CallOption) (*GetClubResponse, error) {
	out := new(GetClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) StartClub(ctx context.Context, in *StartClubRequest, opts ...grpc.CallOption) (*StartClubResponse, error) {
	out := new(StartClubResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/StartClub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetScheduledPicks(ctx context.Context, in *GetScheduledPicksRequest, opts ...grpc.CallOption) (*GetScheduledPicksResponse, error) {
	out := new(GetScheduledPicksResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetScheduledPicks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) SendLoginEmail(ctx context.Context, in *SendLoginEmailRequest, opts ...grpc.CallOption) (*SendLoginEmailResponse, error) {
	out := new(SendLoginEmailResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/SendLoginEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClubServiceClient) GetClubCalendar(ctx context.Context, in *GetClubCalendarRequest, opts ...grpc.CallOption) (*GetClubCalendarResponse, error) {
	out := new(GetClubCalendarResponse)
	err := c.cc.Invoke(ctx, "/watchclub.WatchClubService/GetClubCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchClubServiceServer is the server API for WatchClubService service.
// All implementations must embed UnimplementedWatchClubServiceServer
// for forward compatibility
type WatchClubServiceServer interface {
	// CreateUser creates a new user
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// GetUser gets a user by ID
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// CreateClub creates a new watch club
	CreateClub(context.Context, *CreateClubRequest) (*CreateClubResponse, error)
	// JoinClub adds a user to a club
	JoinClub(context.Context, *JoinClubRequest) (*JoinClubResponse, error)
	// AddPick adds a pick to a club
	AddPick(context.Context, *AddPickRequest) (*AddPickResponse, error)
	// DeletePick removes a pick from a club (only allowed before club starts)
	DeletePick(context.Context, *DeletePickRequest) (*DeletePickResponse, error)
	// GetClub gets details about a club including members and their picks
	GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error)
	// StartClub shuffles all picks and generates the weekly viewing schedule
	StartClub(context.Context, *StartClubRequest) (*StartClubResponse, error)
	// GetScheduledPicks gets the schedule for a club
	GetScheduledPicks(context.Context, *GetScheduledPicksRequest) (*GetScheduledPicksResponse, error)
	// SendLoginEmail sends an account login email
	SendLoginEmail(context.Context, *SendLoginEmailRequest) (*SendLoginEmailResponse, error)
	// GetClubCalendar generates an ICS calendar file for a club's schedule
	GetClubCalendar(context.Context, *GetClubCalendarRequest) (*GetClubCalendarResponse, error)
	mustEmbedUnimplementedWatchClubServiceServer()
}

// UnimplementedWatchClubServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatchClubServiceServer struct {
}

func (UnimplementedWatchClubServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedWatchClubServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedWatchClubServiceServer) CreateClub(context.Context, *CreateClubRequest) (*CreateClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClub not implemented")
}
func (UnimplementedWatchClubServiceServer) JoinClub(context.Context, *JoinClubRequest) (*JoinClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinClub not implemented")
}
func (UnimplementedWatchClubServiceServer) AddPick(context.Context, *AddPickRequest) (*AddPickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPick not implemented")
}
func (UnimplementedWatchClubServiceServer) DeletePick(context.Context, *DeletePickRequest) (*DeletePickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePick not implemented")
}
func (UnimplementedWatchClubServiceServer) GetClub(context.Context, *GetClubRequest) (*GetClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClub not implemented")
}
func (UnimplementedWatchClubServiceServer) StartClub(context.Context, *StartClubRequest) (*StartClubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClub not implemented")
}
func (UnimplementedWatchClubServiceServer) GetScheduledPicks(context.Context, *GetScheduledPicksRequest) (*GetScheduledPicksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduledPicks not implemented")
}
func (UnimplementedWatchClubServiceServer) SendLoginEmail(context.Context, *SendLoginEmailRequest) (*SendLoginEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLoginEmail not implemented")
}
func (UnimplementedWatchClubServiceServer) GetClubCalendar(context.Context, *GetClubCalendarRequest) (*GetClubCalendarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClubCalendar not implemented")
}
func (UnimplementedWatchClubServiceServer) mustEmbedUnimplementedWatchClubServiceServer() {}

// UnsafeWatchClubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchClubServiceServer will
// result in compilation errors.
type UnsafeWatchClubServiceServer interface {
	mustEmbedUnimplementedWatchClubServiceServer()
}

func RegisterWatchClubServiceServer(s grpc.ServiceRegistrar, srv WatchClubServiceServer) {
	s.RegisterService(&WatchClubService_ServiceDesc, srv)
}

func _WatchClubService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_CreateClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).CreateClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/CreateClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).CreateClub(ctx, req.(*CreateClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_JoinClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).JoinClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/JoinClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).JoinClub(ctx, req.(*JoinClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_AddPick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).AddPick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/AddPick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).AddPick(ctx, req.(*AddPickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_DeletePick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).DeletePick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/DeletePick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).DeletePick(ctx, req.(*DeletePickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetClub(ctx, req.(*GetClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_StartClub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).StartClub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/StartClub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).StartClub(ctx, req.(*StartClubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetScheduledPicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledPicksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetScheduledPicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetScheduledPicks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetScheduledPicks(ctx, req.(*GetScheduledPicksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_SendLoginEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).SendLoginEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/SendLoginEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).SendLoginEmail(ctx, req.(*SendLoginEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchClubService_GetClubCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClubCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchClubServiceServer).GetClubCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchclub.WatchClubService/GetClubCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchClubServiceServer).GetClubCalendar(ctx, req.(*GetClubCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchClubService_ServiceDesc is the grpc.ServiceDesc for WatchClubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchClubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchclub.WatchClubService",
	HandlerType: (*WatchClubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _WatchClubService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _WatchClubService_GetUser_Handler,
		},
		{
			MethodName: "CreateClub",
			Handler:    _WatchClubService_CreateClub_Handler,
		},
		{
			MethodName: "JoinClub",
			Handler:    _WatchClubService_JoinClub_Handler,
		},
		{
			MethodName: "AddPick",
			Handler:    _WatchClubService_AddPick_Handler,
		},
		{
			MethodName: "DeletePick",
			Handler:    _WatchClubService_DeletePick_Handler,
		},
		{
			MethodName: "GetClub",
			Handler:    _WatchClubService_GetClub_Handler,
		},
		{
			MethodName: "StartClub",
			Handler:    _WatchClubService_StartClub_Handler,
		},
		{
			MethodName: "GetScheduledPicks",
			Handler:    _WatchClubService_GetScheduledPicks_Handler,
		},
		{
			MethodName: "SendLoginEmail",
			Handler:    _WatchClubService_SendLoginEmail_Handler,
		},
		{
			MethodName: "GetClubCalendar",
			Handler:    _WatchClubService_GetClubCalendar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.proto",
}
